on:
  schedule:
    - cron:  "1,10,20,30,40,50 * * * *"
  workflow_dispatch:

name: chart_create

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Execute Script
        run: |
          Rscript "pfdbot.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/output/plot.png
          git commit -m "output plot" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
